name: 'Chromatic Publish'

on:
  push:
    branches:
      - 'develop'
      - 'main'
    paths:
      - '.storybook/**'
      - 'src/**'

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  storybook:
    name: Chromatic Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: export FONTAWESOME_NPM_AUTH_TOKEN="$FONTAWESOME_NPM_AUTH_TOKEN"
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
