name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    name: Deploy Migrations
    runs-on: ubuntu-22.04
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      PRODUCTION_PROJECT_ID: hudariorhpznzxjzjwhm
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0
      - run: |
          supabase link --project-ref $PRODUCTION_PROJECT_ID
          supabase db push
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build & Deploy
        run: flyctl deploy --config ./fly.production.toml --build-arg FONTAWESOME_NPM_AUTH_TOKEN=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }} --remote-only
